version: '2'
services:
  ftpd_server:
    image: pureftpd
    container_name: pureftpd
    ports:
      - "21:21"
      - "30000-30099:30000-30099"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "$PWD/ftpdata:/home/"
      - "$PWD/passwd:/etc/pure-ftpd/passwd"
# uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
#      - "/folder_on_disk/ssl:/etc/ssl/private/"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: ftpuser
      FTP_USER_PASS: P@assw0rd
      FTP_USER_HOME: /home/ftpuser
      FTP_USER_UID: 33
      FTP_USER_GID: 33
      FTP_MAX_CLIENTS: 50
      FTP_PASSIVE_PORTS: 30000-30099
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
    restart: always
